stages:
  - lint

eslint:
  stage: lint
  #image: node:18
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
  tags:
    - "lint"
  script:
    # Use 
    # Install ESLint in this docker container
    - yarn install
    # Configure ESLint (will read your .eslintrc.ts file)
    # Run ESLint
    - yarn lint:check
